### PR TITLE
Dark Theme

### PR DESCRIPTION
**Pull request by ZainabR11**
**Pull Request Description: Adding Dark/Light Theme**

**Changes Made:**
- Implemented a dark and light theme for the project.
- Created CSS styles for both themes to enhance user experience.
- Added a theme toggle feature to allow users to switch between dark and light modes.
- Ensured accessibility and usability of the themes for all users.

**Why These Changes?**
This pull request introduces a dark and light theme to improve the readability and visual appeal of the project. Users can now choose their preferred theme for a more comfortable browsing experience, especially in low-light environments. This feature enhances user satisfaction and accessibility.

**Demo video**

https://github.com/SwiftGGTeam/the-swift-programming-language-in-chinese/assets/122125525/6cf0fd18-d79c-4258-93f5-a042cbe96f2d

"HACTOBERFEST-ACCEPTED"

### CODE REVIEW

**Comment by ZainabR11** [comment]
@SketchK Kindly review my pull request.

**Comment by SketchK** [comment]
> @SketchK Kindly review my pull request.

Good Job! 
You can add my wechat: 15901231989,
Our website will change recently, maybe you can help us do something, if you have some interest

**Comment by ZainabR11** [comment]
If you like this so, can you please merge the pull request for hacktoberfest 2023?
@SketchK

**Comment by SketchK** [comment]
Can you provide an actual display of the entire site in dark mode?
@ZainabR11

**Comment by ZainabR11** [comment]
I have a question, when i open the website it directs me to the Readme page. So do you want a dark theme for that readme page? I am not able to apply that dark theme to that readme page. Kindly assist. Zainab Rizwan-------- Original message --------From: Zhang SIQI ***@***.***>Date: Sat, 7 Oct 2023, 3:24 pmTo: SwiftGGTeam/the-swift-programming-language-in-chinese ***@***.***>Cc: ZainabR11 ***@***.***>, Mention ***@***.***>Subject: Re: [SwiftGGTeam/the-swift-programming-language-in-chinese] Dark Theme (PR #1241)
Can you provide an actual display of the entire site in dark mode?
@ZainabR11

**Comment by SketchK** [comment]
> @SketchK can you please respond to my email? I have some confusions.

You should add some reviewer
I can't merge it without reviewing

**Pull request closed without merging**
